// Auto-generated by deploy_upx_and_connect.cjs
// UPX Token deployment configuration

export const CONTRACT_CONFIG = {
  UPX_TOKEN_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  NETWORK: "hardhat",
  CHAIN_ID: 31337,
  DEPLOYED_AT: "2025-11-27T10:45:06.420Z",
};

export const SUPPORTED_NETWORKS = {
  ethereum: {
    chainId: 1,
    name: "Ethereum Mainnet",
    rpcUrl: typeof import.meta !== 'undefined' && import.meta.env.VITE_ETH_MAINNET_RPC 
      ? import.meta.env.VITE_ETH_MAINNET_RPC 
      : "https://eth.llamarpc.com",
  },
  polygon: {
    chainId: 137,
    name: "Polygon Mainnet", 
    rpcUrl: typeof import.meta !== 'undefined' && import.meta.env.VITE_POLYGON_MAINNET_RPC
      ? import.meta.env.VITE_POLYGON_MAINNET_RPC
      : "https://polygon.llamarpc.com",
  },
  solana: {
    chainId: 900,
    name: "Solana Mainnet",
    rpcUrl: typeof import.meta !== 'undefined' && import.meta.env.VITE_SOLANA_MAINNET_RPC
      ? import.meta.env.VITE_SOLANA_MAINNET_RPC
      : "https://api.mainnet-beta.solana.com",
  },
  bitcoin: {
    chainId: 0,
    name: "Bitcoin Mainnet",
    rpcUrl: typeof import.meta !== 'undefined' && import.meta.env.VITE_BITCOIN_MAINNET_RPC
      ? import.meta.env.VITE_BITCOIN_MAINNET_RPC
      : "https://blockstream.info/api/",
  },
  goerli: {
    chainId: 5,
    name: "Goerli Testnet",
    rpcUrl: "https://rpc.ankr.com/eth_goerli",
  },
  sepolia: {
    chainId: 11155111,
    name: "Sepolia Testnet",
    rpcUrl: "https://rpc.sepolia.org",
  },
  localhost: {
    chainId: 31337,
    name: "Hardhat Local",
    rpcUrl: "http://127.0.0.1:8545",
  },
};
