/**
 * UNITYPAY + UPX DEPLOY & CONNECT
 * One-paste script to deploy UPX token and connect to UnityPay dashboard
 * Author: Breeze (your voice)
 * Adapted for UnityPay 2045 project structure
 * 
 * Usage:
 * 1) Set your .env with WALLET_PRIVATE_KEY & RPC URLs
 * 2) Run: npx hardhat run scripts/deploy_upx_and_connect.cjs --network <network>
 */

const hre = require("hardhat");
const fs = require("fs");
require("dotenv").config();

async function deployUPX() {
  console.log("💜 Starting UPX deployment...");

  const [deployer] = await hre.ethers.getSigners();
  console.log("📍 Deploying with account:", deployer.address);

  const initialSupply = hre.ethers.parseUnits("1000000", 18); // 1M UPX
  const UPXToken = await hre.ethers.getContractFactory("UPXToken");
  const upx = await UPXToken.deploy(initialSupply);

  await upx.waitForDeployment();
  const contractAddress = await upx.getAddress();
  console.log("✅ UPXToken deployed to:", contractAddress);

  // Save contract address to .env
  const envContent = `\nUNITY_TOKEN_CONTRACT=${contractAddress}\n`;
  fs.appendFileSync(".env", envContent);
  console.log("🔑 Contract address saved to .env as UNITY_TOKEN_CONTRACT");

  return contractAddress;
}

async function connectDashboard(contractAddress) {
  console.log("💻 Connecting UnityPay dashboard to UPX token...");
  
  // Get network info
  const network = await hre.ethers.provider.getNetwork();
  const networkName = network.name === "unknown" ? "localhost" : network.name;
  
  // Update shared config for frontend
  const configPath = "shared/contractConfig.ts";
  const configContent = `// Auto-generated by deploy_upx_and_connect.cjs
// UPX Token deployment configuration

export const CONTRACT_CONFIG = {
  UPX_TOKEN_ADDRESS: "${contractAddress}",
  NETWORK: "${networkName}",
  CHAIN_ID: ${network.chainId.toString()},
  DEPLOYED_AT: "${new Date().toISOString()}",
};

export const SUPPORTED_NETWORKS = {
  ethereum: {
    chainId: 1,
    name: "Ethereum Mainnet",
    rpcUrl: process.env.ETH_RPC_URL || "https://eth.llamarpc.com",
  },
  polygon: {
    chainId: 137,
    name: "Polygon Mainnet", 
    rpcUrl: process.env.POLYGON_RPC_URL || "https://polygon.llamarpc.com",
  },
  goerli: {
    chainId: 5,
    name: "Goerli Testnet",
    rpcUrl: process.env.GOERLI_RPC_URL || "https://rpc.ankr.com/eth_goerli",
  },
  sepolia: {
    chainId: 11155111,
    name: "Sepolia Testnet",
    rpcUrl: process.env.SEPOLIA_RPC_URL || "https://rpc.sepolia.org",
  },
  localhost: {
    chainId: 31337,
    name: "Hardhat Local",
    rpcUrl: "http://127.0.0.1:8545",
  },
};
`;
  
  fs.writeFileSync(configPath, configContent);
  console.log("✅ Shared config updated:", configPath);

  // Also create a JSON deployment record
  const deploymentRecord = {
    contractAddress,
    network: networkName,
    chainId: network.chainId.toString(),
    deployedAt: new Date().toISOString(),
    contractName: "UPXToken",
    initialSupply: "1000000",
  };
  
  const deploymentsDir = "deployments";
  if (!fs.existsSync(deploymentsDir)) {
    fs.mkdirSync(deploymentsDir);
  }
  
  const deploymentPath = `${deploymentsDir}/${networkName}_deployment.json`;
  fs.writeFileSync(deploymentPath, JSON.stringify(deploymentRecord, null, 2));
  console.log("📝 Deployment record saved:", deploymentPath);

  console.log("🎉 UnityPay dashboard is now connected to UPX token.");
  console.log("   Nano Agents can now interact with the token on-chain!");
}

async function main() {
  try {
    console.log("\n💜 ═══════════════════════════════════════════════════");
    console.log("   UNITYPAY 2045 - UPX TOKEN DEPLOYMENT");
    console.log("   One People. One Pay. One Future.");
    console.log("═══════════════════════════════════════════════════════\n");

    const deployedAddress = await deployUPX();
    await connectDashboard(deployedAddress);
    
    console.log("\n💜 ═══════════════════════════════════════════════════");
    console.log("   DEPLOYMENT COMPLETE!");
    console.log("   Contract:", deployedAddress);
    console.log("   Run 'npm run dev' to start the dashboard");
    console.log("═══════════════════════════════════════════════════════\n");
  } catch (e) {
    console.error("❌ Deployment failed:", e);
    process.exit(1);
  }
}

main();
